export const BOOKS_HAS_ERRORED = "BOOKS_HAS_ERRORED";
export const BOOKS_FETCH_DATA_SUCCESS = 'BOOKS_FETCH_DATA_SUCCESS';

export const ADD_OR_UPDATE_BOOK_IN_ORDER = 'ADD_OR_UPDATE_BOOK_IN_ORDER';
export const DELETE_BOOK = 'DELETE_BOOK';
export const CLEAR_ORDER = 'CLEAR_ORDER';

export const ADD_USER = 'ADD_USER';

export const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS';
export const USER_FETCH_DATA_ERROR = 'USER_FETCH_DATA_ERROR';